### ISSUE TITLE
add pmb info

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/schnitzler-mikrofilme-static#10]
... which was my idea after all, so lets do something with it!
https://docs.google.com/spreadsheets/d/1cM9idjHpz-h_sr5DpO_UcVE3bJGI9pu2jwMM3OuJpxA/edit?usp=sharing

**Comment by martinantonmueller** [comment]
yes, i needed convincing. sometimes i'm slow. (other days it's the earth that moves to fast)
