### ISSUE TITLE
favicons and title image

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/schnitzler-mikrofilme-static#2]
well, favicons and title image

**Comment by csae8092** [comment]
@martinantonmueller  *.jpg war auf .gitignore, drum sind deine bilder nicht im repo; vielleicht reicht einmal git pull, git add und git commit damit das title bild auftaucht

**Comment by martinantonmueller** [comment]
die bilder sind doch da! es fehlt nur noch das startbild…
