### ISSUE TITLE
Zitiervorschlag

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-mikrofilme-static#6]
The current solution does not allow to reference pages properly as an URL like https://arthur-schnitzler.github.io/schnitzler-mikrofilme-static/1428127_0006.html only makes sense in reference to Transkribus but is not very user-friendly. 

Two solutions come to my mind:
1) (the big solution) instead of the transkribus-document-ids use the folder name (first three or four characters, starting with "A" or "B", i.e. B023 or A002a or A002. That way one could tell from the URL the folder

2) if solution 1 is not feasible, at least write out whole folder id in the path of the file

**Comment by martinantonmueller** [comment]
Here is a table that contains the document id and the folder title and folder number:
https://docs.google.com/spreadsheets/d/1cM9idjHpz-h_sr5DpO_UcVE3bJGI9pu2jwMM3OuJpxA/edit?usp=sharing

attention: everything except the transkribus-id and Mappennummer2 should be displayed, e.g.

Literarischer Nachlass, A48, Reisebeschreibung, I, Blatt {Pagenumber}

**Comment by csae8092** [comment]
oh das sieht ja sehr schön aus!
