### ISSUE TITLE
Blättern and multiple results

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-mikrofilme-static#7]
A singe map may contain multiple works. If one searches for map "A167" in "Blättern" one gets approx. 12 results. But all of those results link to the content of the first result not the proper one

**Comment by csae8092** [comment]
fix quotation, but first zum Spielplatz mit Ronja

**Comment by martinantonmueller** [comment]
Thank you! I hope R. came back from the playground safe and sound! –
