### ISSUE TITLE
Konkordanz and pmb-no.s

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-mikrofilme-static#9]
This is the updated file:
https://docs.google.com/spreadsheets/d/1cM9idjHpz-h_sr5DpO_UcVE3bJGI9pu2jwMM3OuJpxA/edit#gid=1318818044

Attention, the following rules apply:

* the columns C/D are hidden, the don't need to be displayed, only the new column "Signatur"

* sometimes more than one pmb-number had to be added to a single folder. the first column (TranskribusDocId) therefore is not distinct anymore

**Comment by csae8092** [comment]
> sometimes more than one pmb-number had to be added to a single folder. the first column (TranskribusDocId) therefore is not distinct anymore

this won't work! why not simply do something like 

1416759 | Korrespondenz | Brandes Arkiv |   | Brandes Arkiv, Wassermann | Brandes Arkiv | Brandes Arkiv– Wassermann an Brandes |   | pmb10992 pmb13055
-- | -- | -- | -- | -- | -- | -- | -- | --


adding more pmb-numbers in the pmb-column (separated with whitespace) ?

**Comment by martinantonmueller** [comment]
No problem, will do

**Comment by martinantonmueller** [comment]
The updated file is now online
